<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html>
<!-- meta data & title -->



<link rel="stylesheet" href="./assets/joincss/footer.css">
<link rel="stylesheet" href="./assets/joincss/common.css">
<link rel="stylesheet" href="./assets/joincss/component.css">
<link rel="stylesheet" href="./assets/joincss/resize.css">
<link rel="stylesheet" href="./assets/joincss/swiper.min.css">
<link rel="stylesheet" href="./assets/joincss/css_1050.css"
	type="text/css" media="screen">
<script src="./assets/joincss/jquery-1.12.3.min.js"></script>
<script src="./assets/joincss/serialize.object.js"></script>
<script src="./assets/joincss/json2.js"></script>
<script src="./assets/joincss/CryptoJS.js"></script>
<script type="text/javascript" charset="utf-8"
	src="./assets/joincss/common.js"></script>
<script src="./assets/joincss/common-ui.js"></script>
<script src="./assets/joincss/common-string.js"></script>
<script src="./assets/joincss/common-channel.js"></script>
<script src="./assets/joincss/common-message.js"></script>
<script type="text/javascript"
	src="./assets/joincss/jquery.i18n.properties-1.0.9.js"></script>
<script src="./assets/joincss/util.js"></script>
<script src="./assets/joincss/common-cookie-notice.js"></script>
<script src="./assets/joincss/itraceraf.cfg.js?"></script>
<script src="./assets/joincss/itraceraf.min.js"></script>
<script src="./assets/joincss/swfobject-min.js"></script>
<script src="./assets/joincss/swiper.min.js"></script>
<script src="./assets/joincss/ua.parser.min.js"></script>
<script type="text/javascript">
       if(window.console == undefined){console={log:function(){}};};
       //초기화 데이터(from 서버)
       Common.init('eyJmbHdObyI6InNmbDl1VlFZS0giLCJha1NyblZkdFZhbHVlIjoicCt4SG9uK0dJOHI4RkdZV09QSHBpM3ArNGJSN3FXTnpRYTZOazNpbFRoSVx1MDAzZCJ9.L3VONFpkVWN5UmE2UEY5MitTcWNVVi9udVdqdHlFRDJJdVVoTEU5T0E5MXNzTy9ncnJMeDRrMFJCc3B1Q05PRFovK3Z5ZGNWYjY1TjlSYjhqYkQ2LzlmUmNSSU5hSTdtK3IyR3VtN3pnZXlJcklkNVRkbzJLbGJHYlhaelU4NFdMV2JBY1BvQ2JhM3RjMEtEY0FMbEk0cENWbW5YKzhaRXg2SGRlc2lIeU1wQTc5SHNNTlIvallHV0ZBTGFac0VJSW5zNTR6aUtFQ1lXT2lmTHNFZWxKQ3hpczIxVnNwN2NTS3RFTmQ4NWJWRVhhaVJzd3JTVGF3SFBBVkwzdzhSekdZeTBHdjllcFdsb0lpeVhvQTQrcHlobHJwNnlMSmIra0JsYVFYVHVTc0NQZVgrTng5S0k4UkQ5djQweDUxUnJaUkNPRi9yR2dVNlFKTit2OWhLYzY2dmN5VHpRZURydzdaU2NhTThRamVsRVM2K29lTm1ic1o0c3l6SUovdXhRQjNyczgra2dicWdSVFpBeGM0TFhPYnpYNmhuMzBKQWl4aStpOGdUMjNLRFZkaVFEUFRwdzFoeXJ1Z0dtMWZmZ0tlOUpGRmxmWmV6YkN2b3R2c1VPdlBTc1ZldVNTZjhPZnRJTGZJalAyY0JPNkM1VGF0UER4bVpSdTdmdlhsZ0xTM2lFQm1WNSs1SEJzQXZFMndJcEJ0blNGRytpZFV6WlEzSkNVRkEwTHhUQmxXWGZDRlVzblFseWVCZkJLTlhKRVdZQnk3WUw4U213RWkvNXBpL2Y5U2VFWVpmWklpS0FXMEJtSmhFc3ZMMmZvVzAvSEdZeUdCMVNRNnVvMTF0L2lMTlVkVVF1ZkpZZzkrWEkzc3ByZnBoN0xkR1ZRdU5GcDVNYnBLaU83bzRPZHhYNEZoM2NnVjlrWDJ4d1ZtNkM0MFdMRWROU2ovNzNwZXhWbWVEbFNxbkJZdGpjNGFmSzZwdUprUWUycVJjUElWaTVVb0p2Sm10bWFKdDRMbG9qY0QxSXFSSWRxV3lqdGRkcjhHNk9laXR6VUpBOFlKQ29JbzJCaWlzL29VQWV3V2xuOUlNZTRMZXg3UkZBQTZWdEY0bEE2MEtscG1WdThPeWNCVmFWNjQ1K1pGdWRUckRTNllTWjF6RWVUTWtjdDNPSi9rRDlCdFZnQWttZVd1S1Q1b3FWWCszdUEwalg1R281RzBaRjJYM21nQU1tZkJnMnpXUlFSNVBuTjFRRjdiN244Zk1zWGlNVWV3NmxTZEVpVW1EajBGSmQxaFZTbmFrbTNMdUN0WVgxL0ZjZVJob3A3azQ2Z01kOFpuTDl0OTRkeFJLQmRQK0liU1YyZjdlZy8xNGZUQ3hwTDNMSElNY2hFVmI1dVJJcGEzSXZ3d3hCbnFqNTBYYmRyTHFidGl0RXFRWmFhT0w5emRKb2lJdGNqSzlxSFJKdG44UTUwVmZDZURheDYvQWlmMXM0V3Jsb2NRS3AvK0k2WVg5YzlaVlJFOHNwL1hXVU5CNTdkalpuSTYxelk1QXZnWS9Qc1VqS0NYa2hNUEkraUlvN0xOZTZ5ZmM1QVZ1T05LSVhneVYvZ2wrbWxZN0Q0REtFV0ZkS0Z2YnhrTVUvd0l2WjFYNmZJbE8xcER3ekZWSXk4OGR0TVo1OFh5eHVnNER4NCsrbVE3NlFTRmhwRS9BZUd4TkgxU3ZhSnZwWHR5SGt2YkRGd0VNbDN4TXc3WFgxWXFrV0ZRcXdmMHppd2FiLzVtMjE3SzU5T1VwaVY0M0xHMENCek9YQ1FXajk3VUxSenNnY215RW9zZmxDTDNHOXhPNVc2R2NEZWtqQWh3TnFwbHRjb25BWlF6bTh2SVU3ZVZ2L0JEL0tsUDBQY1NLclZ3V01nNGJnM0hyY2NCZXBwNXh1UjdnRWtpa2Nyd2RNN2IvTWxKUjlBVzlFVDE3M09rMTN2dFhPU0daOE4vSTREektiZ0VraFFmL25OWG1pWm9VNWFUQWRvS2NubURKN3BNSWV0T0JKLzVkelYvQTc4UW4zajliK3FXdjlubXUxcVZpT0NvanBPMk1kV2tKK21zZGVJSjhsZWpKc0UwQ2hZWmRFaDN5c2l4blNCVDYyUkorcHJBSklLc2V6Y1ZheWZlUEtqUUd4eFRuU0hoZGVJK2Fvc0pha1BsVWhIaTB0UXk0ZTVjTGlFNm1MV25xdlBBaEpINTNBREdYWG9tZlFscHZnSGt6eGpjRDNZZ2RsZW54cko1V1dXQ2gvYUFicTBxRnRkSjg5ckF1bUp1cE85QzZodkxTemZZOTl5WEpPTnh4bWpCamE4SVNvOFdrTnl0RVNEYlFsYk1YcThMTHpIT1k3emJVMHB0Y2l5czZsSW5HMHVYbUhwYTZ6eERIdHFzcUhQQ29TS1JJdEdWWWRWU0NPejU3ek8vdnhFL3R2WFZpVWhNSGx2dFd0dklFZWcvN1FjTmd6QmZXeXorSmJPZmMyRUp5N0NBN3FVUnlZWk1NNkt3em9BQTRESzdEQUE2NlhaMzZrYkRZV0xFU1JHb1JMb3JkUE9LbHRuOGtLR3hady90djR2WlFhdGJQVkp3eEdzblpnZENqWUZHcUkvQ0c5V0xObjh5eWorMUNST001MjVkY0VOMXY2MFNla0xSdjBWelFCZ0dJNjhIUlZxN0pzc0RzQmFmZHh6N1FRYW1HMmJiWlJIcVhqS0lXWFk4WXU2Z1htUzkvU21Geko5dTZIU3drWC9LV1hZMDBueHJyb1NoTWJPaG5mSFVnZU1SWUxOdWNPYmhiTmgvNjBOdndtY1pkTGNYUTJSUHU3OG5wNzZZSVJFbHdELzFFSzlBdXlwR3pWWmh3ZHlqTFc3by9RempwL3JMajVPN2poQ3ZpNGw5azhMT05rcGNEUGg4MFBrd3RYdWZyZkVoZktVS2RvbWRTbEN1YkhGTXBYemFZdnBhcUJjMHQ5V0lMUy9XdTFQdHNpODhsbnFEYzY0cTZESG9lWERXM2RaZjhZbWNIbkRWbm1vWUpFWjdQK3kyODJXUjluV3hUcWp6MC9IZTlLOEI4MXNhN2pRSEpxRHRESVg1ODBSZEtmK3RsY2g5V3pHS3FQMDloQXFRZVpUbEFHdVo4OWdYM09Kbm5sN0NYeW56T1ZESUdEajVRY1F3M1BqU0dXc29MTk4yRi8vbXhEVjBQYXkxMzJ0YnRxUTRsbVVUTXY3TDN6S3V3VWdGV05uVVFzUDVBWnoxUmJSMzc2a2VPRmxuWEhrUFZ2WDBTMW5hNVZMMUJEalVaVWVKRTJ2WmpWQldsRjFwZTIrRE1hYnk0M3FGQzZqanEvdEo2Nk4xS2N2djkrYjBFYUZZNUYrNzFmZDkwNU5JODlhdXlQK1lLTmtXcGFaUEdUZmE3SGtKbTl2WnVNMnMzcjJ3ODFNY2FZT3FHcnFqcHEzUEt2eE9udFpuNE9zZnFJVWNoK3l1MG1xaWVMbzhQTVowbmpHQ04xVzB5SHU1Sk5ZQVVWaDRBck5mdGxVb3hDeFdyNEJValoxTkdWL3N5anN0MlZGTG5Yb0owMkVaM2pPajdlU20zUDF4S0VTelFpeXJkeDZoMzJ1cjJQR29jaWN2dmVNRklNUEczaWxUanlHVElkWjdWK1FPemZCd1ZaNzJyNUhnQ2J0eU9PMk9PSVJwZU41cm95dkRrcWNVV0tjZUlPRUVlTW53RFlhWUNpYjBtc3NnTGhiMTNiWlNYMXpwQ1FoYkhkSlBUQ3JOb1BGbzk3aEI4WmQ2SkliWGFidVlrcWZDSXhYWHBmVksxd1lBVytWWUxMVVlBK0xMd2FTalFDVWk1a0dHaHZhQnl3Q3Z4U2IxV0NiVmJQT3BBRnEzTmJsZ2M4YnRuRGlYdFQ2dDNrOWx6QWFXS0FBZVozUnYwenY5MmlhajRZYTlZaFc5dTN4Z01zaWNjUXRUK1haV1R5QWlIWDNhQk15VVRibEd4MmYyZzhqeWYvaGlua0lsRy9GMTUxTGNqRzMvQTNoQnErM3FXMWVRNFhNYW9RUHA5cVNwQnJEOUpiZWdxRDhEcmhHWHphMTFKZUVScE92c1p2MUdENFhicDVWRmdUdURJcEZPWFlmZmlKVWRDMG9LV1JWdVYxVzR5TURFYjMvTVR5elRSMmRDUFBGYmlMSXhYV29OaFUwNHlnTDFZSXlMZE51cW05QS8vZ1ZCVGl3ZVlRcnhoOFEzRUprOGc9',"N");
       
       var langCode = Common.getChannelData().langCode; 	// 언어코드
   
</script>
